### ISSUE TITLE
Give an example of a function with certain properties

### ISSUE THREAD

**Issue by BlackBlueGreens** [IDIAMath/idiamath.github.io#10]
Ask the user to enter a function defined by algebraic expression such that certain properties are in place. Use graphics to plot the surface with corresponding properties before it is evaluated formally.

Property example: partial derivatives at all points with coordinates (t,t) are positive.

**Comment by hgeorgsch** [comment]
This is Question 2.  It needs further work, but this should be defined as separate issues/
