### ISSUE TITLE
Match Properties Question: Screenshots

### ISSUE THREAD

**Issue by hgeorgsch** [IDIAMath/idiamath.github.io#20]
https://idiamath.github.io/question-match-properties.html

Please add screenshots to flesh out one section on how the student interacts with the question.

**Comment by hgeorgsch** [comment]
There should be to substantial sections: one on how the student sees the question and one on how the teacher edits it.

**Comment by BlackBlueGreens** [comment]
i have now done so, but the page for question 1: question-match-plot displays 404 or blank

**Comment by hgeorgsch** [comment]
Some added.  To be reviewed more holistically later.
