### ISSUE TITLE
Make a first tutorial of a 3D JSXGraph STACK question

### ISSUE THREAD

**Issue by hgeorgsch** [IDIAMath/idiamath.github.io#3]
See examples: https://www.ntnu.no/wiki/display/IDIAM/Plugin%3A+Graphical+Questions+3D

1.  Make a STACK question based on one of the examples.
2. Make a tutorial page to explain how the question is made
3.  Make an XML dump of the question and add it to the web pages

**Comment by BlackBlueGreens** [comment]
@hgeorgsch should the question be based one of the 2D examples in the video? or the 3D examples in the first website link:https://jsxgraph.uni-bayreuth.de/~alfred/jsxdev/3D/demo3d.html

since the the page is titled graphical questions + **3d**

**Comment by hgeorgsch** [comment]
There may be useful ideas to find in both 2D and 3D, but we want to make 3D examples, and should those base it on mockups of 3D questions.

**Comment by BlackBlueGreens** [comment]
solution provided here
https://www.ntnu.no/wiki/pages/viewpage.action?pageId=255754655

**Comment by hgeorgsch** [comment]
This needs some further work.  We should have a screenshot or something to get show what we want to achieve.

**Comment by hgeorgsch** [comment]
BTW.  I have moved the page from confluence to github pages

**Comment by hgeorgsch** [comment]
This is superseded by #9 which is more specific.
