### ISSUE TITLE
Question 1 laggy due to storing of graph elements in array

### ISSUE THREAD

**Issue by BlackBlueGreens** [IDIAMath/idiamath.github.io#38]
its very laggy when users scale the 3D view . Due to lack of element tracing in  jsxgraph, im having to manually store the graphs in an array. It seems like there is only one way to do this manually, and that way is very inefficient, and makes the graphics lag when scaling.

**Comment by BlackBlueGreens** [comment]
lack element tracing is a problem, but the lag is more related to a method (mouseover) that runs every time the user cursor is moved a single pixel. 
A timer could be implemented such that every 0.5 seconds, the method does not run for every pixel movement which makes the site lag.
A better solution is to manually check whether using javascript, but jsxgraph know where the 3D function is and we dont...

**Comment by jonasjul** [comment]
I see that the board is quite big as well, 750x1550 - Perhaps the board wouldn't need to be quite this big in a quiz, and scaling it down should help with the performance

**Comment by BlackBlueGreens** [comment]
It is no longer laggy. The code was experimenting with new ideas which did not work and caused the question to lagg instead
