### ISSUE TITLE
User story: given a surface plot and a parameterised model, tune the parameters to make the two fit.

### ISSUE THREAD

**Issue by hgeorgsch** [IDIAMath/idiamath.github.io#5]
Started authoring a question in Stack with the new 3D Jsxgraph library where the question author supplies a function f(x,y) - with three parameters that can/should be tuned by the student.  The author supplies two arrays with the tunable and non-tunable parameters/coefficients (eg. ["a", "b"], ["c"]). A surface plot with the correct function and the tunable function is showed to the student, Stack assesses the students answer by checking if the tuned parameters are within tolerance of the real parameters

**Comment by hgeorgsch** [comment]
Convincing progress.  It may be worth publishing a draft already at this stage @jonasjul 
When that is done, it is easier  for others to review it and make concrete proposals (as new issues).

**Comment by jonasjul** [comment]
Drafts of two questions can be found on iirmoodle-dev:
[tune3D-samples.zip](https://github.com/IDIAMath/idiamath.github.io/files/8926814/tune3D-samples.zip)

Tune 3D is minimal, while Tune 3D quadric is randomized/randomizable.

**Comment by hgeorgsch** [comment]
I have posted the two XML files on the wiki.  Shown on the front page.

**Comment by hgeorgsch** [comment]
Since the first prototypes have been created, further needs should be reported as specific issues, see for instance #13 and #14.
