### ISSUE TITLE
STACK question: Give an algebraic expression to match the given plot

### ISSUE THREAD

**Issue by jonasjul** [IDIAMath/idiamath.github.io#9]
STACK question: Along the lines of tune 3D - The students are shown an unknown function f(x,y) and asked to give the analytical expression of that function. When the function is given by the student it is shown in the same plot or in a separate plot as the goal function with a button toggling the two representations. The student should be able to use one or two tunable parameters in their "guessed" function that they can use sliders in jsxgraph to manipulate when searching for the correct expression. Stack should assess if the given function is sufficiently close to the goal function

**Comment by hgeorgsch** [comment]
@BlackBlueGreens has made the first draft here: https://idiamath.github.io/question-match-properties.html

Please add some screenshot to give a quick impression of how the student meets the question, @BlackBlueGreens .  Secondly, the XML link is broken. An XML file is placed in the root, but the filename is wrong too.

The tutorial page should contain two thorough sections.  Firstly, how the student should engage with the question, what is tested, and what is the learning outcome.  Secondly, how the teacher edits the question.  The code seems to be there, but the code needs explanation and rationale.  It is possible that @jonasjul and I have to look at that.

**Comment by hgeorgsch** [comment]
This is question 2.  To be reviewed and completed.
